[workspace]
resolver = "2"

default-members = [
    "conjure_oxide",
    "crates/conjure_core",
    "solvers/kissat",
    "solvers/minion",
    "crates/uniplate",
]

members = [
    "conjure_oxide",
    "crates/conjure_core",
    "crates/enum_compatability_macro",
    "crates/conjure_macros",
    "crates/uniplate",
    "crates/uniplate_derive",
    "solvers/kissat",
    "solvers/minion",
    "solvers/chuffed", "tools/ci-test-benchmarks",
]

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1
