[workspace]
resolver = "2"

default-members = [
    "conjure_oxide",
    "crates/conjure_core",
    "crates/conjure_rules",
    "solvers/kissat",
    "solvers/minion",
]

members = [
    "conjure_oxide",
    "crates/conjure_core",
    "crates/doc_solver_support",
    "crates/conjure_rules_proc_macro",
    "crates/conjure_rules",
    "solvers/kissat",
    "solvers/minion",
    "solvers/chuffed",
]

[workspace.lints.clippy]
unwrap_used = "warn"
expect_used = "warn"

[profile.dev]
codegen-units = 1

[profile.release]
codegen-units = 1
