[package]
name = "benchmarks-visualizer"
version = "0.1.0"
authors = ["Pedro Gronda Garrigues"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.1" # for conjure native test parallelization

[lints]
workspace = true
