name: "Code and Documentation Coverage (PR)"

on:
  pull_request:
    paths:
      - conjure_oxide/**
      - solvers/**
      - crates/**
      - .github/actions/code-coverage.yml
  workflow_dispatch:

env:
  rust_release: nightly

jobs:
  coverage:
    name: "Generate Code Coverage Reports"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get Sha
        id: sha
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]] 
          then
            echo -e "sha=${{ github.event.pull_request.head.sha }}" >> "$GITHUB_OUTPUT"
            echo -e "sha=${{ github.event.pull_request.head.sha }}"
          else 
            echo -e "sha=${{ github.sha }}" >> "$GITHUB_OUTPUT"
            echo -e "sha=${{ github.sha }}"
          fi

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target
            solvers/minion/vendor
            solvers/chuffed/vendor

          key: ${{ runner.os }}-${{ env.rust_release }}-${{ github.event.repository.updated_at }}
          restore-keys: ${{ runner.os }}-${{ env.rust_release }}

      - name: Install rust ${{ env.rust_release }}
        run: rustup update ${{ env.rust_release }} && rustup default ${{ env.rust_release }}
      
      - uses: ./.github/actions/install-conjure
        with: 
          os_arch: linux
          version: 2.5.1
          
      - name: Generate coverage reports
        run: |
          ./tools/coverage.sh
          
      - run: |
          mkdir -p deploy/
          cp -r target/debug/coverage/* deploy/     # html
          cp target/debug/lcov.info deploy/         # used for comments

      - name: Archive code coverage results for deployment
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-${{ steps.sha.outputs.sha }}
          path: deploy/**
      